version: '3.8'

services:
  ollama:
    image: ollama/ollama:0.12.3
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      - mi_red_compartida
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

volumes:
  ollama:

networks:
  mi_red_compartida:
    external: true
